version: "2"

run:
  timeout: 5m

linters:
  enable:
    - staticcheck
  disable:
    - errcheck
  
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unused
        - staticcheck
