package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/dl-alexandre/gdrv/internal/discovery"
)

const (
	// CodeGeneratedHeader is the standard header for generated files
	CodeGeneratedHeader = `// Code generated by discovery-checker from Google Discovery API.
// DO NOT EDIT.
// 
// Generated: {{ .Timestamp }}
// Source: {{ .DiscoveryURL }}
// Version: {{ .APIVersion }}
//
// Changes since last generation:
{{ range .Changes }}//   - {{ . }}
{{ end }}

`
	// typeTemplate generates Go struct definitions from discovery schemas
	typeTemplate = `{{ comment .ServiceTitle }}
// 
// Code generated from Google Discovery API. DO NOT EDIT.

package {{ .Package }}

{{ if .NeedsTime }}import "time"

{{ end }}
{{ range .Schemas }}
{{ if .IsEnum }}
{{ comment .Description }}
type {{ .GoName }} string

const (
{{ $schema := . }}
{{ range .EnumValues }}
	{{ enumConstName $schema.GoName . }} {{ $schema.GoName }} = {{ printf "%q" . }}
{{ end }}
)
{{ else }}
{{ comment .Description }}
type {{ .GoName }} struct {
{{ range .Fields }}
	{{ .GoName }} {{ .Type }} ` + "`json:\"{{ .JSONName }}" + `{{ if .OmitEmpty }},omitempty{{ end }}\"` + "`" + ` {{ comment .Description }}
{{ end }}
}
{{ end }}
{{ end }}
`
	// descriptorTemplate generates endpoint metadata
	descriptorTemplate = `{{ comment .ServiceTitle }}
// 
// Code generated from Google Discovery API. DO NOT EDIT.

package {{ .Package }}

// ServiceDescriptor contains metadata for the {{ .ServiceName }} API
type ServiceDescriptor struct {
	Name        string
	Version     string
	BaseURL     string
	RootURL     string
	ServicePath string
}

// Service returns the service descriptor for {{ .ServiceName }}
var Service = ServiceDescriptor{
	Name:        "{{ .ServiceName }}",
	Version:     "{{ .Version }}",
	BaseURL:     "{{ .BaseURL }}",
	RootURL:     "{{ .RootURL }}",
	ServicePath: "{{ .ServicePath }}",
}

type MethodDescriptor struct {
	Name       string
	HTTPMethod string
	Path       string
	Parameters []ParameterDescriptor
}

type ParameterDescriptor struct {
	Name     string
	Type     string
	Location string
	Required bool
}

type ResourceDescriptor struct {
	Name    string
	Methods map[string]MethodDescriptor
}

var Resources = map[string]ResourceDescriptor{
{{ range .Resources }}
	{{ printf "%q" .Name }}: {{ .GoName }},
{{ end }}
}

{{ range .Resources }}
{{ comment .Description }}
var {{ .GoName }} = ResourceDescriptor{
	Name: {{ printf "%q" .Name }},
	Methods: map[string]MethodDescriptor{
{{ range .Methods }}
		{{ printf "%q" .Name }}: {
			Name:       {{ printf "%q" .Name }},
			HTTPMethod: {{ printf "%q" .HTTPMethod }},
			Path:       {{ printf "%q" .Path }},
			Parameters: []ParameterDescriptor{
{{ range .Parameters }}
				{Name: {{ printf "%q" .Name }}, Type: {{ printf "%q" .Type }}, Location: {{ printf "%q" .Location }}, Required: {{ .Required }}},
{{ end }}
			},
		},
{{ end }}
	},
}
{{ end }}
`
)

// GeneratorConfig holds configuration for code generation
type GeneratorConfig struct {
	PackagePrefix     string
	PackageName       string
	OutputDir         string
	IncludeTimestamp  bool
	IncludeSourceInfo bool
	GenerateComments  bool
}

// TypeGenerator generates Go types from discovery schemas
type TypeGenerator struct {
	config GeneratorConfig
	tmpl   *template.Template
}

// NewTypeGenerator creates a new type generator with loaded templates
func NewTypeGenerator(config GeneratorConfig) (*TypeGenerator, error) {
	tmpl, err := template.New("types").Funcs(templateFuncs()).Parse(typeTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing type template: %w", err)
	}

	return &TypeGenerator{
		config: config,
		tmpl:   tmpl,
	}, nil
}

// Generate creates Go type definitions from a discovery document
func (g *TypeGenerator) Generate(doc *discovery.DiscoveryDocument, serviceName string) ([]byte, error) {
	data := typeTemplateData{
		Package:       g.packageName(serviceName),
		GeneratedTime: time.Now().UTC().Format(time.RFC3339),
		ServiceName:   doc.Name,
		ServiceTitle:  doc.Title,
		Version:       doc.Version,
		DiscoveryURL:  fmt.Sprintf("https://%s.googleapis.com/$discovery/rest?version=%s", serviceName, doc.Version),
		Schemas:       convertSchemas(doc.Schemas),
	}
	data.NeedsTime = schemasNeedTime(data.Schemas)

	var buf bytes.Buffer
	if err := g.tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}

	// Format with gofmt
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted with error - caller can decide
		return buf.Bytes(), fmt.Errorf("formatting generated code: %w", err)
	}

	return formatted, nil
}

// WriteToFile writes generated code to the appropriate file
func (g *TypeGenerator) WriteToFile(serviceName string, content []byte) error {
	dir := filepath.Join(g.config.OutputDir, serviceName)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating directory: %w", err)
	}

	path := filepath.Join(dir, "types.go")
	if err := os.WriteFile(path, content, 0644); err != nil {
		return fmt.Errorf("writing file: %w", err)
	}

	return nil
}

// DescriptorGenerator generates endpoint descriptors
type DescriptorGenerator struct {
	config GeneratorConfig
	tmpl   *template.Template
}

// NewDescriptorGenerator creates a new descriptor generator
func NewDescriptorGenerator(config GeneratorConfig) (*DescriptorGenerator, error) {
	tmpl, err := template.New("descriptors").Funcs(templateFuncs()).Parse(descriptorTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing descriptor template: %w", err)
	}

	return &DescriptorGenerator{
		config: config,
		tmpl:   tmpl,
	}, nil
}

// Generate creates endpoint descriptors from a discovery document
func (g *DescriptorGenerator) Generate(doc *discovery.DiscoveryDocument, serviceName string) ([]byte, error) {
	data := descriptorTemplateData{
		Package:       g.packageName(serviceName + "descriptors"),
		GeneratedTime: time.Now().UTC().Format(time.RFC3339),
		ServiceName:   doc.Name,
		ServiceTitle:  doc.Title,
		Version:       doc.Version,
		DiscoveryURL:  fmt.Sprintf("https://%s.googleapis.com/$discovery/rest?version=%s", serviceName, doc.Version),
		BaseURL:       doc.BaseURL,
		RootURL:       doc.RootURL,
		ServicePath:   doc.ServicePath,
		Resources:     convertResources(doc.Resources),
	}

	var buf bytes.Buffer
	if err := g.tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}

	// Format with gofmt
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("formatting generated code: %w", err)
	}

	return formatted, nil
}

// WriteToFile writes generated descriptors to the appropriate file
func (g *DescriptorGenerator) WriteToFile(serviceName string, content []byte) error {
	dir := filepath.Join(g.config.OutputDir, serviceName+"descriptors")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating directory: %w", err)
	}

	path := filepath.Join(dir, "descriptors.go")
	if err := os.WriteFile(path, content, 0644); err != nil {
		return fmt.Errorf("writing file: %w", err)
	}

	return nil
}

func (g *TypeGenerator) packageName(serviceName string) string {
	if g.config.PackageName != "" {
		return packageName(g.config.PackageName)
	}
	return packageName(serviceName)
}

func (g *DescriptorGenerator) packageName(serviceName string) string {
	if g.config.PackageName != "" {
		return packageName(g.config.PackageName)
	}
	return packageName(serviceName)
}

// Template data structures
type typeTemplateData struct {
	Package       string
	GeneratedTime string
	ServiceName   string
	ServiceTitle  string
	Version       string
	DiscoveryURL  string
	Schemas       []SchemaInfo
	NeedsTime     bool
}

type descriptorTemplateData struct {
	Package       string
	GeneratedTime string
	ServiceName   string
	ServiceTitle  string
	Version       string
	DiscoveryURL  string
	BaseURL       string
	RootURL       string
	ServicePath   string
	Resources     []ResourceInfo
}

type SchemaInfo struct {
	Name        string
	GoName      string
	Description string
	Fields      []FieldInfo
	IsEnum      bool
	EnumValues  []string
}

type FieldInfo struct {
	Name        string
	GoName      string
	Type        string
	JSONName    string
	Description string
	Required    bool
	OmitEmpty   bool
}

type ResourceInfo struct {
	Name        string
	GoName      string
	Description string
	Methods     []MethodInfo
}

type MethodInfo struct {
	Name         string
	GoName       string
	HTTPMethod   string
	Path         string
	Description  string
	Parameters   []ParameterInfo
	RequestType  string
	ResponseType string
	Scopes       []string
}

type ParameterInfo struct {
	Name     string
	GoName   string
	Type     string
	Location string // "path" or "query"
	Required bool
}

// Helper functions for template
type TypeMapper struct {
	schemas map[string]discovery.Schema
}

func NewTypeMapper(schemas map[string]discovery.Schema) *TypeMapper {
	return &TypeMapper{schemas: schemas}
}

func (m *TypeMapper) MapSchema(schema discovery.Schema) string {
	if schema.Type == "array" && schema.Items != nil {
		return "[]" + m.MapSchema(*schema.Items)
	}
	return m.MapJSONType(schema.Type, schema.Format, schema.Ref)
}

func (m *TypeMapper) MapJSONType(jsonType, format, ref string) string {
	// Handle $ref references
	if ref != "" {
		return toGoName(ref)
	}

	// Map JSON Schema types to Go types
	switch jsonType {
	case "string":
		if format == "date-time" {
			return "time.Time"
		}
		if format == "date" {
			return "string" // Could be civil.Date
		}
		if format == "int64" || format == "uint64" {
			return format
		}
		return "string"
	case "integer":
		if format == "int64" {
			return "int64"
		}
		return "int"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		return "[]interface{}" // Would need item type info
	case "object":
		return "map[string]interface{}"
	case "any":
		return "interface{}"
	default:
		return "interface{}"
	}
}

// templateFuncs returns functions available in templates
func templateFuncs() template.FuncMap {
	return template.FuncMap{
		"toGoName":      toGoName,
		"enumConstName": enumConstName,
		"toJSONName": func(s string) string {
			return s
		},
		"comment": formatComment,
	}
}

// toGoName converts a discovery name to Go naming convention
func toGoName(name string) string {
	name = strings.TrimSpace(name)
	if name == "" {
		return "Value"
	}

	var parts []string
	var current strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			current.WriteRune(r)
		default:
			if current.Len() > 0 {
				parts = append(parts, current.String())
				current.Reset()
			}
		}
	}
	if current.Len() > 0 {
		parts = append(parts, current.String())
	}
	if len(parts) == 0 {
		return "Value"
	}

	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}

	result := strings.Join(parts, "")
	if result == "" {
		return "Value"
	}
	if result[0] >= '0' && result[0] <= '9' {
		result = "Value" + result
	}
	if isGoKeyword(strings.ToLower(result)) {
		result += "Value"
	}
	return result
}

func enumConstName(typeName, value string) string {
	name := toGoName(value)
	if name == "Value" {
		name = "Unknown"
	}
	return typeName + name
}

func isGoKeyword(name string) bool {
	switch name {
	case "break", "default", "func", "interface", "select", "case", "defer", "go", "map", "struct",
		"chan", "else", "goto", "package", "switch", "const", "fallthrough", "if", "range",
		"type", "continue", "for", "import", "return", "var":
		return true
	default:
		return false
	}
}

// formatComment formats a string as a Go comment
func formatComment(s string) string {
	if s == "" {
		return ""
	}
	// Escape special characters and wrap
	s = strings.ReplaceAll(s, "*/", "*\\/")
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		lines[i] = "// " + line
	}
	return strings.Join(lines, "\n")
}

// packageName converts service name to Go package name
func packageName(service string) string {
	name := strings.ToLower(toGoName(service))
	if name == "" {
		return "generated"
	}
	return name
}

// convertSchemas transforms discovery schemas to template-friendly format
func convertSchemas(schemas map[string]discovery.Schema) []SchemaInfo {
	var result []SchemaInfo

	// Sort schema names for stable output
	var names []string
	for name := range schemas {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		schema := schemas[name]
		info := SchemaInfo{
			Name:        name,
			GoName:      toGoName(name),
			Description: schema.Description,
		}

		// Handle enums
		if len(schema.Enum) > 0 {
			info.IsEnum = true
			info.EnumValues = schema.Enum
		}

		// Convert properties - sort property names
		var propNames []string
		for propName := range schema.Properties {
			propNames = append(propNames, propName)
		}
		sort.Strings(propNames)

		for _, propName := range propNames {
			prop := schema.Properties[propName]
			field := FieldInfo{
				Name:        propName,
				GoName:      toGoName(propName),
				JSONName:    propName,
				Description: prop.Description,
				Required:    contains(schema.Required, propName),
				OmitEmpty:   !contains(schema.Required, propName),
			}

			mapper := NewTypeMapper(schemas)
			field.Type = mapper.MapSchema(prop)

			info.Fields = append(info.Fields, field)
		}

		result = append(result, info)
	}
	return result
}

// convertResources transforms discovery resources to template-friendly format
func convertResources(resources map[string]discovery.Resource) []ResourceInfo {
	var result []ResourceInfo

	var names []string
	for name := range resources {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		resource := resources[name]
		info := ResourceInfo{
			Name:        name,
			GoName:      toGoName(name),
			Description: name,
		}

		var methodNames []string
		for methodName := range resource.Methods {
			methodNames = append(methodNames, methodName)
		}
		sort.Strings(methodNames)

		for _, methodName := range methodNames {
			method := resource.Methods[methodName]
			displayName := method.ID
			if displayName == "" {
				displayName = methodName
			}
			methodInfo := MethodInfo{
				Name:        displayName,
				GoName:      toGoName(methodName),
				HTTPMethod:  method.HTTPMethod,
				Path:        method.Path,
				Description: method.Description,
				Scopes:      method.Scopes,
			}

			if method.Request != nil {
				methodInfo.RequestType = method.Request.Ref
			}
			if method.Response != nil {
				methodInfo.ResponseType = method.Response.Ref
			}

			// Convert parameters
			var paramNames []string
			for paramName := range method.Parameters {
				paramNames = append(paramNames, paramName)
			}
			sort.Strings(paramNames)

			for _, paramName := range paramNames {
				param := method.Parameters[paramName]
				paramInfo := ParameterInfo{
					Name:     paramName,
					GoName:   toGoName(paramName),
					Type:     param.Type,
					Location: param.Location,
					Required: param.Required,
				}
				methodInfo.Parameters = append(methodInfo.Parameters, paramInfo)
			}

			info.Methods = append(info.Methods, methodInfo)
		}

		result = append(result, info)
	}
	return result
}

func schemasNeedTime(schemas []SchemaInfo) bool {
	for _, schema := range schemas {
		for _, field := range schema.Fields {
			if field.Type == "time.Time" {
				return true
			}
		}
	}
	return false
}

func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}
